from setuptools import setup, find_packages

setup(
    name="veco",
    version="0.1.0",
    description="Vectorization & RAG Toolkit",
    packages=find_packages(),
    python_requires=">=3.12",
    install_requires=[
        "numpy==2.2.6",
        "scipy>=1.13.0,<1.16",
        "numba==0.61.2",
        "faiss-cpu==1.11.0.post1",
        "moviepy==2.2.1",
        "openai-whisper==20240930",
        "sentence-transformers==5.0.0",
        "ollama==0.5.1",
        "librosa==0.10.2.post1",
        "soundfile",
        "sounddevice==0.4.7",
        "webrtcvad-wheels==2.0.12",
        "pytesseract==0.3.13",
        "Pillow==11.0.0",
        "pdfplumber==0.11.7",
        "python-docx==1.2.0",
        "python-pptx==1.0.2",
        "speechbrain",
        "tqdm==4.66.5",
        "transformers>=4.56,<5",
        "sentencepiece",
        "sacremoses",
    ],
    extras_require={
        "torch-cu129": [
            "torch==2.8.0",
            "torchaudio==2.8.0",
        ],
        "dev": [
            "pytest",
            "black",
            "ruff",
            "mypy",
        ],
    },
)
